In [45]:
#vivian's attempt
import numpy as np
def simulate_prizedoor (nsim):
    sims=np.random.randint(0,3,size=nsim)
    return sims

def simulate_guess (nsim):
    #guesses= np.zeros(nsim, dtype=np.int)
    guesses= np.random.randint(0,3,size=nsim)
    return guesses


def goat_door(prizedoors, guesses):
    option=np.arange(0,3)
    #print option.size
    i=0
    goats=np.zeros(prizedoors.size, dtype=np.int)
    for i in range(prizedoors.size):  #range does not include the maximum
        k=0
        for k in range(option.size):
            #print "option",option[k],"prizedoor",prizedoors[i],"guesses",guesses[i],"i",i           
            if ((option[k]!=prizedoors[i])&(option[k]!=guesses[i])):
                goats[i]=option[k] 
                #print "goats",goats
                break
    return goats

def switch_guess (guesses,goatdoors):
    result = np.random.randint(0, 3, guesses.size)
    while True:
        bad = (result == goatdoors) | (result == guesses) #returns an array of true or false boolean judgements
        #print "bad: ", bad
        if not bad.any():
            return result
        result[bad] = np.random.randint(0, 3, bad.sum()) 
        
def win_percentage(guesses,prizedoors):
    win=(guesses == prizedoors).mean()*100
    return win

nsim=10000
prizedoors=simulate_prizedoor(nsim)
guesses=simulate_guess(nsim)
goatdoors=goat_door(prizedoors,guesses)
switched=switch_guess (guesses,goatdoors)

#print prizedoors, "prizes"
#print guesses,"guesses"
#print goatdoors,"goats"
#print switch_guess (guesses,goatdoors),"switched guesses"
print win_percentage(guesses,prizedoors),"win percent"
print win_percentage(switched,prizedoors),"win percent"

In [21]:
#generalize to n doors and 1 prize; open x goat doors x<=n-2
#vivian's attempt
import numpy as np
def simulate_prizedoor (nsim,ndoor):
    sims=np.random.randint(0,ndoor,size=nsim)
    return sims

def simulate_guess (nsim,ndoor):
    #guesses= np.zeros(nsim, dtype=np.int)
    guesses= np.random.randint(0,ndoor,size=nsim)
    return guesses


def goat_door(prizedoors, guesses,ndoor,ngoat):
    result=np.tile(np.random.randint(0, ndoor, ngoat),(prizedoors.size,1))
    for i in range (prizedoors.size):
        result[i] = np.random.randint(0, ndoor, ngoat)
    
    print result
    print result[0]
    
    i=0
    for i in range (result.size):
        while True:
            temp=result[i]
            bad = (temp == prizedoors) | (temp == guesses) 
            if not bad.any():
                result[i]=temp
                break
            temp[bad] = np.random.randint(0, ndoor, bad.sum())
    return result
        
        
def switch_guess (guesses,goatdoors,ndoor):
    result = np.random.randint(0, ndoor, guesses.size)
    while True:
        bad = (result == goatdoors) | (result == guesses) 
        if not bad.any():
            return result
        result[bad] = np.random.randint(0, ndoor, bad.sum()) 
        
def win_percentage(guesses,prizedoors):
    win=(guesses == prizedoors).mean()*100
    return win

nsim=7
ndoor=10
ngoat=3
prizedoors=simulate_prizedoor(nsim,ndoor)
guesses=simulate_guess(nsim,ndoor)
goatdoors=goat_door(prizedoors,guesses,ndoor,ngoat)
switched=switch_guess (guesses,goatdoors,ndoor)

print prizedoors, "prizes"
print guesses,"guesses"
print goatdoors,"goats"
#print switch_guess (guesses,goatdoors),"switched guesses"
#print win_percentage(guesses,prizedoors),"win percent: no switch"
#print win_percentage(switched,prizedoors),"win percent: switch"

[[4 0 5]
 [6 7 3]
 [8 6 7]
 [4 4 3]
 [5 3 8]
 [7 5 1]
 [1 6 9]]
[4 0 5]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:26: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.


AttributeError: 'bool' object has no attribute 'any'

In [43]:
#reference answer
import numpy as np
def simulate_prizedoor(nsim):
    return np.random.randint(0, 3, (nsim))

def simulate_guess(nsim):
    return np.zeros(nsim, dtype=np.int)

def goat_door(prizedoors, guesses):
    result = np.random.randint(0, 3, prizedoors.size)
    #print result
    while True:
        bad = (result == prizedoors) | (result == guesses) #returns an array of true or false boolean judgements
        #print "bad: ", bad
        if not bad.any():
            return result
        result[bad] = np.random.randint(0, 3, bad.sum()) #generates new values for the bad cases, 
                                                        #indice match with the original results array, 
                                                        #essentially this updates the results array with 
                                                        #bad cases replaced by newly generated random results
        #print "result[bad]: ",result[bad]
        #print "result: ", result
        
def switch_guess(guesses, goatdoors):
    result = np.zeros(guesses.size)
    switch = {(0, 1): 2, (0, 2): 1, (1, 0): 2, (1, 2): 1, (2, 0): 1, (2, 1): 0} #dictionary
    for i in [0, 1, 2]:
        for j in [0, 1, 2]:
            mask = (guesses == i) & (goatdoors == j) #returns an array of boolean judgements, 
                                                    #judging which of the [(guesses, goatdoors)] pairs match with the [i, j];
                                                    #essentially this detects the values in [(guesses, goatdoors)];
                                                    #for a given (i,j), if it matches with (guesses[x], goatdoors[x]), then mask[x]==true; 
                                                    #otherwise mask[x]==false
            #print "i:",i,"j:",j,"mask:",mask
            if not mask.any():
                continue
            #print "the thing",np.ones_like(result) * switch[(i, j)]
            #print "result",result
            result = np.where(mask, np.ones_like(result) * switch[(i, j)], result)  # if there are matches, i.e. mask.sum>0, i.e. [(guesses[x],goatdoors[x])]=(i,j);
                                                                                    #switch[(i, j)] finds the corresponding switched guesses from the dictionary named *switch*;
                                                                                    #np.ones_like(result) * switch[(i, j)] generates an array of the length of result, 
                                                                                    #value of each element in the array == corresponding switched guesses;
                                                                                    #np.where()updates the result array at indice where mask==true with value from 
                                                                                    #the newly generated array of corresponding switched guesses
                                                                                    
    return result


def win_percentage(guesses, prizedoors):
    return 100 * (guesses == prizedoors).mean()

nsim=10000
prizedoors=simulate_prizedoor(nsim)
guesses=simulate_guess(nsim)
goatdoors=goat_door(prizedoors,guesses)
switched=switch_guess (guesses,goatdoors)

#print prizedoors, "prizes"
#print guesses,"guesses"
#print goatdoors,"goats"
#print switch_guess (guesses,goatdoors),"switched guesses"
print win_percentage(guesses,prizedoors),"win percent"
print win_percentage(switched,prizedoors),"win percent"