In [3]:
import numpy as np

In [47]:
def simulate_prizedoor (nsim):
    sims=np.random.randint(0,3,size=nsim)
    return sims

def simulate_guess (nsim):
    #guesses= np.zeros(nsim, dtype=np.int)
    guesses= np.random.randint(0,3,size=nsim)
    return guesses


def goat_door(prizedoors, guesses):
    option=np.arange(0,3)
    #print option.size
    i=0
    goats=np.zeros(prizedoors.size, dtype=np.int)
    for i in range(prizedoors.size):  #range does not include the maximum
        k=0
        for k in range(option.size):
            #print "option",option[k],"prizedoor",prizedoors[i],"guesses",guesses[i],"i",i           
            if ((option[k]!=prizedoors[i])&(option[k]!=guesses[i])):
                goats[i]=option[k] 
                #print "goats",goats
                break
    return goats

def switch_guess (guesses,goatdoors):
    result = np.random.randint(0, 3, guesses.size)
    while True:
        bad = (result == goatdoors) | (result == guesses) #returns an array of true or false boolen judgements
        #print "bad: ", bad
        if not bad.any():
            return result
        result[bad] = np.random.randint(0, 3, bad.sum()) 

In [48]:
prizedoors=simulate_prizedoor(7)
guesses=simulate_guess(7)
goatdoors=goat_door(prizedoors,guesses)

print prizedoors, "prizes"
print guesses,"guesses"
print goatdoors,"goats"
print switch_guess (guesses,goatdoors),"switched guesses"


[0 1 1 0 2 1 0] prizes
[0 0 1 1 1 1 0] guesses
[1 2 0 2 0 0 1] goats
[2 1 2 0 2 2 2] switched guesses


In [20]:
def simulate_prizedoor(nsim):
    return np.random.randint(0, 3, (nsim))

def simulate_guess(nsim):
    return np.zeros(nsim, dtype=np.int)

def goat_door(prizedoors, guesses):
    result = np.random.randint(0, 3, prizedoors.size)
    #print result
    while True:
        bad = (result == prizedoors) | (result == guesses) #returns an array of true or false boolen judgements
        #print "bad: ", bad
        if not bad.any():
            return result
        result[bad] = np.random.randint(0, 3, bad.sum()) #generates new values for the bad cases, 
                                                            #indice match with the original results array, 
                                                            #essentially this updates the results array with 
                                                            #bad cases replaced by newly generated random results
        #print "result[bad]: ",result[bad]
        #print "result: ", result
        
#not quite clear
def switch_guess(guesses, goatdoors):
    result = np.zeros(guesses.size)
    switch = {(0, 1): 2, (0, 2): 1, (1, 0): 2, (1, 2): 1, (2, 0): 1, (2, 1): 0}
    for i in [0, 1, 2]:
        for j in [0, 1, 2]:
            mask = (guesses == i) & (goatdoors == j)
            if not mask.any():
                continue
            result = np.where(mask, np.ones_like(result) * switch[(i, j)], result)
    return result
